// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/handler_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/KV2013/url-shortner-go/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLService is a mock of URLService interface.
type MockURLService struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceMockRecorder
	isgomock struct{}
}

// MockURLServiceMockRecorder is the mock recorder for MockURLService.
type MockURLServiceMockRecorder struct {
	mock *MockURLService
}

// NewMockURLService creates a new mock instance.
func NewMockURLService(ctrl *gomock.Controller) *MockURLService {
	mock := &MockURLService{ctrl: ctrl}
	mock.recorder = &MockURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLService) EXPECT() *MockURLServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockURLService) GetByID(id string) (*model.URL, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.URL)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockURLServiceMockRecorder) GetByID(id any) *MockURLServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockURLService)(nil).GetByID), id)
	return &MockURLServiceGetByIDCall{Call: call}
}

// MockURLServiceGetByIDCall wrap *gomock.Call
type MockURLServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockURLServiceGetByIDCall) Return(arg0 *model.URL, arg1 bool) *MockURLServiceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockURLServiceGetByIDCall) Do(f func(string) (*model.URL, bool)) *MockURLServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockURLServiceGetByIDCall) DoAndReturn(f func(string) (*model.URL, bool)) *MockURLServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveURL mocks base method.
func (m *MockURLService) SaveURL(url string) (*model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", url)
	ret0, _ := ret[0].(*model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockURLServiceMockRecorder) SaveURL(url any) *MockURLServiceSaveURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockURLService)(nil).SaveURL), url)
	return &MockURLServiceSaveURLCall{Call: call}
}

// MockURLServiceSaveURLCall wrap *gomock.Call
type MockURLServiceSaveURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockURLServiceSaveURLCall) Return(arg0 *model.URL, arg1 error) *MockURLServiceSaveURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockURLServiceSaveURLCall) Do(f func(string) (*model.URL, error)) *MockURLServiceSaveURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockURLServiceSaveURLCall) DoAndReturn(f func(string) (*model.URL, error)) *MockURLServiceSaveURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
