// Code generated by reset; DO NOT EDIT.

package model

func (u *URL) Reset() {
	if u == nil {
		return
	}
	u.Original = ""
	u.Short = ""
	u.UserID = ""
	u.DeletedFlag = false
}

func (a *APIErrorResponse) Reset() {
	if a == nil {
		return
	}
	a.Error = ""
}
